"""Marc's PDB entries, and one short link that shows all of them at RCSB.

WHY NOT AN AUTHOR SEARCH. The obvious link is an RCSB search on his name, and it
was measured to find 9 of his 78 entries. Most of his structural-genomics work
was deposited under the Joint Center for Structural Genomics as the author, not
as individuals, so a name search quietly undercounts by nearly nine tenths.

So the link asks RCSB for the entries by ID, which returns exactly the 78 (also
measured). That URL is about 1,500 characters, far too long for a language model
to copy faithfully into an answer, so the app serves it behind a short, stable
route, /pdb, and the model only ever has to write that.

The ID list lives in pdb_entries.json, regenerated by scripts/build_pdb_links.py.
"""

from __future__ import annotations

import json
import urllib.parse
from functools import lru_cache
from pathlib import Path

DATA = Path(__file__).with_name("pdb_entries.json")


@lru_cache(maxsize=1)
def load(path: str = str(DATA)) -> dict:
    return json.loads(Path(path).read_text())


def rcsb_search_url(ids: list[str]) -> str:
    """An RCSB search page listing exactly these entries, newest release first."""
    request = {
        "query": {"type": "terminal", "service": "text",
                  "parameters": {"attribute": "rcsb_entry_container_identifiers.entry_id",
                                 "operator": "in", "value": list(ids)}},
        "return_type": "entry",
        "request_options": {
            "paginate": {"start": 0, "rows": 100},
            "sort": [{"sort_by": "rcsb_accession_info.initial_release_date",
                      "direction": "desc"}],
        },
    }
    return ("https://www.rcsb.org/search?request="
            + urllib.parse.quote(json.dumps(request, separators=(",", ":"))))
